s=set()
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
a=int(input("Enter the number:"))
s.add(a)
print(s)