fruits=[]
f1=input("Enter the fruit:")
fruits.append(f1)
f2=input("Enter the 2 fruit:")
fruits.append(f2)
f3=input("Enter the 3 fruit:")
fruits.append(f3)
f4=input("Enter the 4 fruit:")
fruits.append(f4)
f5=input("Enter the 5 fruit:")
fruits.append(f5)
print("THE final list is:",fruits)
