marks=[]
m1=int(input("Enter the marks of the student:"))
m2=int(input("Enter the marks of the student:"))
m3=int(input("Enter the marks of the student:"))
m4=int(input("Enter the marks of the student:"))
m5=int(input("Enter the marks of the student:"))
m6=int(input("Enter the marks of the student:"))
m7=int(input("Enter the marks of the student:"))
m8=int(input("Enter the marks of the student:"))
marks.append(m1)
marks.append(m2)
marks.append(m3)
marks.append(m4)
marks.append(m5)
marks.append(m6)
marks.append(m7)
marks.append(m8)
marks.sort()
print("THe final list is:",marks)
