s1=input("Enter the string:")
print(len(s1))
print(s1.endswith("i"))
print(s1.endswith("shikha",3,9))
print(s1.startswith("Sh"))
print(s1.capitalize())
print("hello world".title())
print("Shubhangi is a good girl..".rstrip("."))
print("ice cream".find("ece"))
print("Trust the god".replace("god","Universe"))
print("Hello.beautiful.world.here.I.am".split("."))
print(s1.count("is"))
print(s1.isalnum())
print(s1.swapcase())